name: PR标题规范检查

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    name: 检查PR标题格式
    runs-on: ubuntu-latest
    steps:
      - name: 检查PR标题
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            release
          typesDescription: |
            feat: 新功能
            fix: 修复bug
            docs: 文档更新
            style: 代码格式修改（不影响代码运行的变动）
            refactor: 代码重构（既不是新增功能，也不是修改bug的代码变动）
            perf: 性能优化
            test: 增加测试
            build: 构建过程或辅助工具的变动
            ci: CI配置文件和脚本的变动
            chore: 其他修改（不修改src或测试文件）
            revert: 回滚之前的提交
            release: 发布新版本
          requireScope: false
          subjectPattern: ^[A-Za-z\u4e00-\u9fa5].+$
          subjectPatternError: |
            PR标题格式不正确！

            正确的格式是：<type>: <subject>
            - type必须是上述类型之一
            - subject必须以字母或中文开头

            正确的例子：
            ✅ feat: 添加登录功能
            ✅ fix: 修复首页加载慢的问题
            ✅ docs: 更新README文档
            ✅ style: 优化代码格式

            你的PR标题是:${{ github.event.pull_request.title }}

      - name: 添加检查结果摘要
        if: always()
        run: |
          echo "### PR标题检查结果 :label:" >> $GITHUB_STEP_SUMMARY
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ PR标题格式正确" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ PR标题格式不正确" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### 标题格式要求" >> $GITHUB_STEP_SUMMARY
            echo "格式：\`<type>: <subject>\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "允许的type类型：" >> $GITHUB_STEP_SUMMARY
            echo "- feat: 新功能" >> $GITHUB_STEP_SUMMARY
            echo "- fix: 修复bug" >> $GITHUB_STEP_SUMMARY
            echo "- docs: 文档更新" >> $GITHUB_STEP_SUMMARY
            echo "- style: 代码格式修改" >> $GITHUB_STEP_SUMMARY
            echo "- refactor: 代码重构" >> $GITHUB_STEP_SUMMARY
            echo "- perf: 性能优化" >> $GITHUB_STEP_SUMMARY
            echo "- test: 增加测试" >> $GITHUB_STEP_SUMMARY
            echo "- build: 构建相关" >> $GITHUB_STEP_SUMMARY
            echo "- ci: CI配置相关" >> $GITHUB_STEP_SUMMARY
            echo "- chore: 其他修改" >> $GITHUB_STEP_SUMMARY
            echo "- revert: 回滚提交" >> $GITHUB_STEP_SUMMARY
            echo "- release: 发布版本" >> $GITHUB_STEP_SUMMARY
          fi
